# Generated by Django 3.2.16 on 2022-12-01 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pageapp', '0002_alter_place_img'),
    ]

    operations = [
        migrations.CreateModel(
            name='review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('person', models.CharField(max_length=250)),
                ('image', models.ImageField(upload_to='pics')),
                ('comment', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='place',
            name='img',
            field=models.ImageField(upload_to='pics'),
        ),
    ]
