# Generated by Django 3.2.16 on 2022-12-01 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pageapp', '0003_auto_20221201_2054'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='image',
            field=models.ImageField(upload_to='picture'),
        ),
    ]
